apiVersion: apps/v1
kind: Deployment
metadata:
  name: cookbook-be-deployment
  namespace: cookbook
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 998898571931.dkr.ecr.us-east-1.amazonaws.com/vpbank-hackathon:be-v22
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_APP
              valueFrom:
                secretKeyRef:
                  name: cookbook-secret
                  key: FLASK_APP
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: cookbook-secret
                  key: JWT_SECRET_KEY
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: cookbook-secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: cookbook-secret
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cookbook-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cookbook-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: cookbook-secret
                  key: DB_NAME
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
