apiVersion: v1
kind: Service
metadata:
  name: cookbook-be-service
  namespace: cookbook
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
