apiVersion: v1
kind: Service
metadata:
  name: cookbook-mysql-service
  namespace: cookbook
spec:
  selector:
    app: cookbook-mysql
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
